partner_name=testing-dsd-8215
country=IN
state=Kar
locality=Blr
organisation=testing-dsd-8215
email_id=usereugo1@example.com
common_name=testcommon-name
keystore_password=mosip@123
CAcertvalidityperiod=500
Partnercertvalidityperiod=499
