[DEFAULT]
partner_name=mpartner-default-esignet-m161
country=IN
state=Kar
locality=Ban
organisation=IITB
email_id=mosip@example.com
common_name=MOSIPTEST
keystore_password=mosip123
daysCA=400
daysSubCA=400
daysPartner=400
