csv:
  filename: images.txt
  has_header: no

docker:
  username: 
  token:
  destination_organization:
  registry_url: https://index.docker.io/v1/
  imageExitUrl: https://registry.hub.docker.com/v2/

process:
  count: 3
