csv:
  filename: images.txt
  has_header: no

docker:
  username: <docker hub username>
  token: <docker hub token>
  destination_organization: <docker hub destination org> 
  registry_url: https://index.docker.io/v1/

process:
  count: 3

