EXISTING_REPO_URL=https://github.com/mahesh-binayak/commons.git
NEW_REPO_URL=https://github.com/mahesh-binayak/otpmanager.git
FILES_TO_MOVE=".github db_scripts .gitignore pom.xml README.md LICENSE kernel/kernel-otpmanager-service"
