name: Helm-release Preparation.

on:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: 'Repo URL ( EX. mosip/< repo name > )'
        required: true
      REPO_BRANCH:
        description: 'Repo Branch'
        required: true
      VERSION_PAIR:
        description: 'Versions for Chart.yaml and install.sh files, format: CHART_VERSION,INSTALL_CHART_VERSION'
        required: true
        type: string
      IMAGE_TAG:
        description: 'Tag to update in values.yaml'
        required: true
      BASE:
        description: 'base branch for PR'
        required: true
      COMMIT_MESSAGE:
        description: 'commit message'
        required: true   
jobs:
  helm-release-preparation:
    uses: mosip/kattu/.github/workflows/helm-release.yaml@master
    with:
      REPO_URL: ${{ inputs.REPO_URL }}
      REPO_BRANCH: ${{ inputs.REPO_BRANCH }}
      VERSION_PAIR: ${{ inputs.VERSION_PAIR }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      BASE: ${{ inputs.BASE }}
      COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
    secrets:
      ACTION_PAT: ${{ secrets.ACTION_PAT }}
