name: Release/pre-release Preparation.

on:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: 'Repo URL ( EX. mosip/< repo name > )'
        required: true
        type: string
      REPO_BRANCH:
        description: 'Repo Branch'
        required: true
        type: string
      RELEASE_TAG:
        description: 'Tag to update'
        required: true
        type: string
      SNAPSHOT_TAG:
        description: 'Tag to be replace'
        required: true
        type: string
      BASE:
        description: 'Base branch for PR'
        required: true
        type: string
      COMMIT_MESSAGE:
        description: 'Commit message'
        required: true
        type: string
jobs:
  maven-release-preparation:
    uses: Prafulrakhade/kattu/.github/workflows/release-changes.yml@master
    with:
      REPO_URL: ${{ inputs.REPO_URL }}
      REPO_BRANCH: ${{ inputs.REPO_BRANCH }}
      RELEASE_TAG: ${{ inputs.RELEASE_TAG }}
      SNAPSHOT_TAG: ${{ inputs.SNAPSHOT_TAG }}
      BASE: ${{ inputs.BASE }}
      COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
    secrets:
      ACTION_PAT: ${{ secrets.ACTION_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MOSIP_WEBHOOK_URL }}
