name: Verify GitHub Secrets
on:
  push:
    branches:
      - release-1.2.0.1
  pull_request:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo secrets (redacted)
      run: |
        echo ${OSSRH_SNAPSHOT_URL} >> a.txt
        echo ${OSSRH_USER} >> a.txt
        echo ${OSSRH_SECRET} >> a.txt
        echo ${OSSRH_TOKEN} >> a.txt
        echo ${GPG_SECRET} >> a.txt
        cat a.txt
      env:
        OSSRH_SNAPSHOT_URL: ${{ secrets.OSSRH_SNAPSHOT_URL }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_SECRET: ${{ secrets.OSSRH_SECRET }}
