name: Verify GitHub Secrets

on:
  push:
    branches:
      - release-1.2.0.1
  pull_request:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo secrets
      run: |
        echo "OSSRH_SNAPSHOT_URL: ${OSSRH_SNAPSHOT_URL:0:4}****"
        echo "OSSRH_USER: ${OSSRH_USER}"
        echo "OSSRH_SECRET: ${OSSRH_SECRET:0:4}****"
        echo "OSSRH_TOKEN: ${OSSRH_TOKEN:0:4}****"
        echo "GPG_SECRET: ${GPG_SECRET:0:4}****"
      env:
        OSSRH_SNAPSHOT_URL: ${{ secrets.OSSRH_SNAPSHOT_URL }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_SECRET: ${{ secrets.GPG_SECRET }}
